import { getServerSession } from 'next-auth'
import ClientProvider from '../components/ClientProvider'
import Login from '../components/Login'
import SessionProvider from '../components/SessionProvider'
import Sidebar from '../components/Sidebar'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

type Props = {
  children: React.ReactNode
}

export default async function RootLayout({ children }: Props) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (<>
            <Login />
          </>)
            :
            (
              <div className='flex'>

                <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[15rem]'>
                  <Sidebar />
                </div>

                <ClientProvider/>

                <div className='bg-[#343541] flex-1'>
                  {children}
                </div>
              </div>
            )
          }

        </SessionProvider>
      </body>
    </html>
  )
}
